# Generated by Django 2.2.4 on 2020-01-16 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 11, 57, 57, 387644, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
